/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Categories: () => import('#controllers/categories_controller'),
  Folders: () => import('#controllers/folders_controller'),
  ItemPhotos: () => import('#controllers/item_photos_controller'),
  Items: () => import('#controllers/items_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
